# fly.toml app configuration file generated for meeting-scheduler-client on 2025-05-13T14:46:54-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'meeting-scheduler-client'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 5179
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[env]
  REACT_APP_API_BASE_URL = "https://meeting-scheduler-server.fly.dev"
  REACT_APP_FRONTEND_URL = "https://meeting-scheduler-client.fly.dev" 

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
